### ISSUE TITLE
POX replaceResultRequest message doesn't contain mandatory message identifier

### ISSUE THREAD

**Issue by ashirman** [IMSGlobal/basiclti-util-java#30]
LTI 1.1 POX replaceResultRequest header has following XSD 

```
<xs:complexType name="imsx_RequestHeaderInfo.Type" mixed="false">
    <xs:annotation>
        <xs:documentation source="umldocumentation">...</xs:documentation>
    </xs:annotation>
    <xs:sequence>
        <xs:element ref="imsx_version" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="imsx_messageIdentifier" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="imsx_sendingAgentIdentifier" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
</xs:complexType>
```

so there must be 1 message identidier imsx_messageIdentifier but replaceResultRequest has not it. see full schema definition here
https://www.imsglobal.org/lti/media/ltiv1p1/OMSv1p0_LTIv1p1Profile_SyncXSD_v1p0.xsd

as result some LMS with schema verification can't accept replaceResultRequest POX message generated by this library. E.g. Blackboard 9.1.201404.160205 return HTTP 500 status with stack trace on the server site as following:

2017-01-13 11:21:27 -0500 - Failure/Unsupported error sent to LTI Grade Callback request:  - blackboard.blti.outcomes.NoPOXDataException: //lti:imsx_messageIdentifier
	at blackboard.blti.outcomes.POXDocument.throwIfEmpty(Unknown Source)
	at blackboard.blti.outcomes.POXDocument.getXPathValue(Unknown Source)
	at blackboard.blti.outcomes.POXDocument.getTagValue(Unknown Source)
	at blackboard.blti.outcomes.consumer.POXRequest.getMessageIdentifier(Unknown Source)
	at blackboard.blti.outcomes.consumer.POXOutcomesRequestHandler.setMessageIdentifiers(Unknown Source)
	at blackboard.blti.outcomes.consumer.POXOutcomesRequestHandler.handleSuccess(Unknown Source)
	at blackboard.blti.outcomes.consumer.POXOutcomesRequestHandler.handleReplaceResult(Unknown Source)
	at blackboard.blti.outcomes.consumer.POXOutcomesRequestHandler.handle(Unknown Source)
	at blackboard.webapps.gradebook2.lti.LTI11GradingEndPointServlet.doPost(LTI11GradingEndPointServlet.java:26)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)

**Comment by akotynski** [comment]
@pfgray is there any chance to marge PR #31 connected with this issue?

**Comment by Prasannaa-P** [comment]
@ashirman / @pfgray   Can you please get this merged?

**Comment by pfgray** [comment]
Sorry this has taken so long.

I need @ashirman to sign a Contributor's License Agreement form before I can accept this PR.

The CLA form can be requested by sending an email to info@imsglobal.org

**Comment by cayhorstmann** [comment]
You also need to add the required `<language>` element to `resultScore` before `textString`:

```
<resultScore><language>en</language>"+
			"						<textString>%s</textString>"+
"					</resultScore>"+

**Comment by pfgray** [comment]
Version `1.2.0` has been released which adds support for the `messageIdentifier` field
